### ISSUE TITLE
Cannot find module ‘react-native/Libraries/LogBox/LogBox’ from ‘setup.js’ 

### ISSUE THREAD

**Issue by apappas1129** [expo/expo#10414]
### Summary of Issue 
running `jest` causes error about `LogBox` on `setup.js` 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
`expo diagnostics` :

System:
```
    OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4819257
    npmPackages:
      expo: ^37.0.12 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed
```

`package.json`

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "lint": "eslint src/**/*.js App.js",
    "test": "jest",
    "test:coverage": "jest --verbose --updateSnapshot --watch --coverage && open ./coverage/lcov-report/index.html"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/native": "^5.4.0",
    "@react-navigation/stack": "^5.3.7",
    "base-64": "^0.1.0",
    "expo": "^37.0.12",
    "firebase": "^7.14.4",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-web": "~0.11.7",
    "expo-constants": "~9.0.0",
    "expo-permissions": "~8.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0",
    "eslint": "^7.9.0",
    "eslint-plugin-react": "^7.20.6",
    "jest-expo": "^39.0.0",
    "react-test-renderer": "^16.13.1"
  },
  "private": true,
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)"
    ]
  }
}
```
 
### Steps to Reproduce

1. Checkout the branch named "jesting" from here https://github.com/apappas1129/firestore-chat/tree/jesting
2. Run `npm run test`

### Expected Behavior vs Actual Behavior
`npm run test` or `jest` should run successfully. Instead I get this error:

```
Cannot find module ‘react-native/Libraries/LogBox/LogBox’ from ‘setup.js’
    at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:299:11)
    at Object. (node_modules/jest-expo/src/preset/setup.js:155:6)
```

**Comment by byCedric** [comment]
Hi @apappas1129, thanks for the report. Unfortunately, I couldn't reproduce this issue with the repo you provided. Maybe your node_modules somehow got a different `react-native` installed? You should be able to double-check this by running `npm ci` and/or adding a script to github actions, to test your project on github's machines.

Something like this should work:

in `.github/workflows/test.yml`
```
name: Test
on: [pull_request]
jobs:
  test:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Test project
        run: npm test
``` 

Hope this helps!
