### ISSUE TITLE
Expo 42 requires expo-updates, although OTA updates are disabled and package is not included anywhere

### ISSUE THREAD

**Issue by cseelus** [expo/expo#13473]
### Summary

After upgrading to Expo 42, running `expo start -c` and opening the app in iOS simulator, I got this error message, although my app does not use `expo-updates` and has worked in the past fine w/o it:

```bash
Failed building JavaScript bundle.
Unable to resolve module expo-updates from /project_path/node_modules/sentry-expo/build/sentry.js: expo-updates could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  22 | exports.init = exports.Native = void 0;
  23 | const react_native_1 = require("react-native");
> 24 | const Updates = __importStar(require("expo-updates"));
     |                                       ^
  25 | const expo_constants_1 = __importStar(require("expo-constants"));
  26 | const Application = __importStar(require("expo-application"));
  27 | const integrations_1 = require("@sentry/integrations");
```

Not sure if [this issue](https://github.com/expo/expo/pull/13458) is related.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```yaml
Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.3.0 - /opt/homebrew/bin/fish
    Binaries:
      Node: 14.17.1 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 6.14.13 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0
      react: ^17.0.2 => 17.0.2
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

-
