### ISSUE TITLE
[iOS][Facebook] Not redirecting back to app after Facebook.logInWithReadPermissionsAsync through facebook app

### ISSUE THREAD

**Issue by jwoo92** [expo/expo#14090]
### Summary

This is exactly the same bug as seen in https://github.com/expo/expo/issues/6112 following the exact same steps as seen in https://github.com/expo/expo/issues/6112#issuecomment-581936976 with the only notable difference being this case is using `expo-dev-client`.

I tested the regular managed and bare workflows under the same working environment without `expo-dev-client` and had no issues.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

- expo@42.0.1
- expo-dev-client@0.4.7
- expo-facebook@11.3.1

### Environment

```yaml
  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/User/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Project Setup:

<details>
  <summary><strong>1. Create project + install dependencies</strong></summary>

<br>

Run the following commands in your CLI:

```shell
expo init # name: my-app | template: bare (Managed workflow) 
cd my-app
expo install expo-facebook expo-dev-client
```
</details>

<details>
  <summary><strong>2. Update the following files</strong></summary>

<br>

```json
// ./app.json

{
  "expo": {
    "name": "MyApp",
    "slug": "myapp",
    "privacy": "hidden",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "facebookScheme": "fb<FB-APP-ID>",
    "facebookAppId": "<FB-APP-ID>",
    "facebookDisplayName": "<FB-APP-NAME>",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "bundle.id.here"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}

```

```js
// ./App.js

import { StatusBar } from "expo-status-bar";
import React from "react";
import { Alert, Button, StyleSheet, Text, View } from "react-native";
import * as Facebook from "expo-facebook";
import Constants from "expo-constants";

async function login() {
  try {
    await Facebook.initializeAsync({
      appId: Constants.manifest.facebookAppId,
      appName: Constants.manifest.facebookDisplayName
    });

    const { type, token, expirationDate, permissions, declinedPermissions } =
      await Facebook.logInWithReadPermissionsAsync({
        permissions: ["public_profile"],
      });

    if (type === "success") {
      // Get the user's name using Facebook's Graph API
      const response = await fetch(
        `https://graph.facebook.com/me?access_token=${token}`
      );

      Alert.alert("Logged in!", `Hi ${(await response.json()).name}!`);
    } else {
      // type === 'cancel'
      console.log("Facebook Cancelled");
    }
  } catch ({ message }) {
    Alert.alert(`Facebook Login Error: ${message}`);
  }
}

export default function App() {
  return (
    <View style={styles.container}>
      <Button title="Login with Facebook" onPress={login} />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```
</details>

<details>
  <summary><strong>3. Build</strong></summary>

<br>

Run either the Debug or Release build command in your CLI (both have been tested):

_Note: if asked, enter same bundle ID used in your ./app.json_

```shell
# release build
$ expo run:ios --no-bundler --configuration Release --device
```

```shell
# debug build
$ expo run:ios --device
```
</details>

---

In-App Experience:

Before interacting with the app, you must be logged out of Facebook in the browser and signed into the native Facebook app.

In the expo example-app, press the _Login with Facebook_ button. You will see a pop-up asking to navigate to the Facebook app - press this and authenticate in the Facebook app. Then you will be redirected back to our expo example-app with the webview still in place.

In your code the `Facebook.logInWithReadPermissionsAsync` promise will not resolve. You will see the experience fly to the Facebook app, then back to the webview popup and stopping here. What it should be doing is closing the webview at this point, as it does in non development-client based expo apps.

### Stacktrace (if a crash is involved)

N/A
