### ISSUE TITLE
[expo-image-picker] Could not find com.theartofdev.edmodo:android-image-cropper:2.8.0

### ISSUE THREAD

**Issue by aprilmintacpineda** [expo/expo#14391]
### Summary

Changing `jcenter()` with `mavenCentral()` throws this error:

```yaml
BUILD FAILED in 1m 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDevDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDevDebugAssets'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find com.theartofdev.edmodo:android-image-cropper:2.8.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/theartofdev/edmodo/android-image-cropper/2.8.0/android-image-cropper-2.8.0.pom
       - file:/Users/aprilmintacpineda/.m2/repository/com/theartofdev/edmodo/android-image-cropper/2.8.0/android-image-cropper-2.8.0.pom
       - file:/Users/aprilmintacpineda/projects/rn-proj-pronetplat-aa/node_modules/react-native/android/com/theartofdev/edmodo/android-image-cropper/2.8.0/android-image-cropper-2.8.0.pom
       - file:/Users/aprilmintacpineda/projects/rn-proj-pronetplat-aa/node_modules/jsc-android/dist/com/theartofdev/edmodo/android-image-cropper/2.8.0/android-image-cropper-2.8.0.pom
       - https://dl.google.com/dl/android/maven2/com/theartofdev/edmodo/android-image-cropper/2.8.0/android-image-cropper-2.8.0.pom
       - https://www.jitpack.io/com/theartofdev/edmodo/android-image-cropper/2.8.0/android-image-cropper-2.8.0.pom
       - https://maven.google.com/com/theartofdev/edmodo/android-image-cropper/2.8.0/android-image-cropper-2.8.0.pom
     Required by:
         project :app > project :expo-image-picker
   > Could not find com.android.volley:volley:1.1.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/android/volley/volley/1.1.1/volley-1.1.1.pom
       - file:/Users/aprilmintacpineda/.m2/repository/com/android/volley/volley/1.1.1/volley-1.1.1.pom
       - file:/Users/aprilmintacpineda/projects/rn-proj-pronetplat-aa/node_modules/react-native/android/com/android/volley/volley/1.1.1/volley-1.1.1.pom
       - file:/Users/aprilmintacpineda/projects/rn-proj-pronetplat-aa/node_modules/jsc-android/dist/com/android/volley/volley/1.1.1/volley-1.1.1.pom
       - https://dl.google.com/dl/android/maven2/com/android/volley/volley/1.1.1/volley-1.1.1.pom
       - https://www.jitpack.io/com/android/volley/volley/1.1.1/volley-1.1.1.pom
       - https://maven.google.com/com/android/volley/volley/1.1.1/volley-1.1.1.pom
     Required by:
         project :app > project :react-native-google-places > com.google.android.libraries.places:places:1.1.0
```

Current work around is to not move to `mavenCentral()`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```yaml
Expo CLI 4.11.0 environment info:
  System:
    OS: macOS 11.3
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /Users/aprilmintacpineda/.rvm/gems/ruby-3.0.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 24, 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  npmPackages:
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
  Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Install expo-image-picker on react-native 0.65 and replace `jcenter()` with `mavenCentral()` on your `android/build.gradle`.
