### ISSUE TITLE
[expo-gl][SDK 44][Android] GLView causes crash on startup

### ISSUE THREAD

**Issue by sandlands** [expo/expo#15811]
### Summary

When trying to run the GLView [demo app](https://docs.expo.dev/versions/latest/sdk/gl-view/) with Expo SDK 44 in managed workflow (Expo GO) on Android, the app crashes immediately. (On SDK 43, it works fine.)

Phones:
- Samsung Galaxy A32 (SM-A326B)
- Google Pixel 4a

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.0.16 - /usr/local/bin/bash
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 8.3.0 - /usr/local/bin/npm
      Watchman: 2022.01.03.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.43.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

```
expo init [choose blank (Typescript)]
expo install expo-gl
```
Replace App.tsx with [demo](https://docs.expo.dev/versions/latest/sdk/gl-view/) from GLView docs (see below).
```
expo start
```

App.tsx:
```ts
import React from 'react';
import { View } from 'react-native';
import { GLView } from 'expo-gl';

export default function App() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <GLView style={{ width: 300, height: 300 }} onContextCreate={onContextCreate} />
    </View>
  );
}

function onContextCreate(gl) {
  gl.viewport(0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight);
  gl.clearColor(0, 1, 1, 1);

  // Create vertex shader (shape & position)
  const vert = gl.createShader(gl.VERTEX_SHADER);
  gl.shaderSource(
    vert,
    `
    void main(void) {
      gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
      gl_PointSize = 150.0;
    }
  `
  );
  gl.compileShader(vert);

  // Create fragment shader (color)
  const frag = gl.createShader(gl.FRAGMENT_SHADER);
  gl.shaderSource(
    frag,
    `
    void main(void) {
      gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
    }
  `
  );
  gl.compileShader(frag);

  // Link together into a program
  const program = gl.createProgram();
  gl.attachShader(program, vert);
  gl.attachShader(program, frag);
  gl.linkProgram(program);
  gl.useProgram(program);

  gl.clear(gl.COLOR_BUFFER_BIT);
  gl.drawArrays(gl.POINTS, 0, 1);

  gl.flush();
  gl.endFrameEXP();
}
```

**Comment by byCedric** [comment]
Hi @sandlands! Thanks for writing in. Unfortunately, I couldn't reproduce a crash with the repro and context. I tested upgrading from SDK 43 to 44 with the example code and ran it on Expo Go for both SDKs. Can you provide a small working repository with this issue?

Can you try and find and share the logcat crash log? That might point to something. You can [find a bit more info here](https://docs.expo.dev/workflow/debugging/#my-production-app-is-crashing) if you aren't sure what logcat is. 

Hope this helps!

**Comment by sandlands** [comment]
Hi @byCedric! Thanks for looking into it. That's strange. I just reproduced it again with a brand new app and the instructions above. Could it be phone-related? Could you share your `expo diagnostics`? Maybe we can find some differences...

I also prepared a logcat: [expo-gl-sdk44-logcat.txt.zip](https://github.com/expo/expo/files/7844502/expo-gl-sdk44-logcat.txt.zip). I have attached it. I started the app around 08:09. You can find the `--------- beginning of crash` section at `01-11 08:09:05.431`.

BTW My phone software is up-to-date and I'm using Expo GO 2.23.2.

If you have more questions, feel free to ask.

Kind regards, Sander

**Comment by sandlands** [comment]
A little bit more information:
- I was able to reproduce it on a Google Pixel 4a as well
- I can also reproduce it with a completely empty onContextCreate method (`function onContextCreate(gl) {}`)
- When I set the `width` and `height` to `0` (or otherwise give no space to the component), the crash does **not** occur. However, when I set it back and save (to make Expo GO update the app), the app crashes immediately.

**Comment by SerSerch** [comment]
I have the same problem after upgrading to expo 44.
The problem is in the cyclic import of files.
GLView just added loads and the application crashed.

**Comment by gnoel** [comment]
I'm having the same problem.
It was working fine on SDK 43 but not after upgrading to SDK 44.

**Comment by kulmajaba** [comment]
Tested this on iOS and Android devices, same setup. Expo SDK 44, create a new project, `expo install expo-gl` and paste the minimal example app. Running via Expo Go.

- iOS simulator, iOS 15.0: works
- iOS device, iPad 8th gen, iOS 15.2: works
- Android emulator, Pixel 4 model, Android 10/Q = API 29: works
- Android emulator, Pixel 4 model, Android 11/R = API 30: works
- Android emulator, Pixel 4 model, Android 12/S = API 31: works
- Android device, Samsung Galaxy S20 FE 5G, Android 12/S = API 31:  **chrashes**
- Android device, Nokia 3.4: Android 10/Q = API 29: works
- Android device, Nokia 3.4: Android 11/R = API 30: **chrashes**

From my limited testing it seems like the issue occurs only on Android devices with API 30 or higher.

**Comment by SerSerch** [comment]
@kulmajaba No, this problem is also on iOs XR (which i have) and android emulator and android devices. The problem lies in the cyclic import of files. In a default application, without unnecessary imports, everything works.

**Comment by kulmajaba** [comment]
@SerSerch Can you post your setup, the devices and emulators you tested and a minimal example that reproduces the issue? As I said I could not get Android Emulators to crash so there is probably some difference in either the setup or the code.

**Comment by NikitaDudin** [comment]
Testing on device in bare workflow, expo SDK 44:

- Realme GT5 with Android 11: **crash**.
- Realme GT5 with Android 12: **crash**.

adb log:
```
Process uptime: 0s
Cmdline: com.test.gl
pid: 30545, tid: 30583, name: mqt_js  >>> com.test.gl <<<
uid: 10455
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2072656666756a
    x0  0000000000000020  x1  000000687589e640  x2  0000006875800000  x3  0000000000000002
    x4  000000000000009e  x5  000000000000007d  x6  00000068660d2f24  x7  54454c4b524f575f
    x8  7420726566667542  x9  8ecd6e3e25861d92  x10 000000000000009e  x11 0000000000000001
    x12 000000000000dae8  x13 d0643ac2e7721fff  x14 00000071ac1e82e0  x15 00000000745f2d6d
    x16 00000072f8130bd0  x17 00000072f8121c14  x18 0000000000000000  x19 b4000071b3504a00
    x20 b40000721127f800  x21 0000042c0000042c  x22 00000071acb3c000  x23 00000071acb3b2b0
    x24 00000071acb3c000  x25 00000071acb3b588  x26 00000072262fe270  x27 000000000000000b
    x28 00000071acb3b480  x29 00000071acb3b320
    lr  00000068641051a0  sp  00000071acb3b2a0  pc  00000068641051b8  pst 0000000060001000
backtrace:
      #00 pc 00000000000691b8  /data/app/~~HFZQGcYyu4ci8IDxCxnGwA==/com.test.gl-de_4ToXawG4fZZeyZMpC3A==/lib/arm64/libexpo-gl.so (expo::gl_cpp::EXGLContext::prepareContext(facebook::jsi::Runtime&, std::__ndk1::function<void ()>)+476) (BuildId: deaed3376f22bd6e2c76f387c5493ff6426d38aa)
      #01 pc 000000000004d2a8  /data/app/~~HFZQGcYyu4ci8IDxCxnGwA==/com.test.gl-de_4ToXawG4fZZeyZMpC3A==/lib/arm64/libexpo-gl.so (UEXGLContextPrepare+144) (BuildId: deaed3376f22bd6e2c76f387c5493ff6426d38aa)
      #02 pc 00000000000ba390  /data/app/~~HFZQGcYyu4ci8IDxCxnGwA==/com.test.gl-de_4ToXawG4fZZeyZMpC3A==/lib/arm64/libexpo-gl.so (Java_expo_modules_gl_cpp_EXGL_EXGLContextPrepare+208) (BuildId: deaed3376f22bd6e2c76f387c5493ff6426d38aa)
      #03 pc 0000000000222244  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: c1533ab4f1f17e564063e13bf04bf126)
      #04 pc 0000000000211d0c  /apex/com.android.art/lib64/libart.so (nterp_helper+1948) (BuildId: c1533ab4f1f17e564063e13bf04bf126)
      #05 pc 00000000003dc082  /data/app/~~HFZQGcYyu4ci8IDxCxnGwA==/com.test.gl-de_4ToXawG4fZZeyZMpC3A==/oat/arm64/base.vdex (expo.modules.gl.GLContext$1.run+70)
      #06 pc 00000000005224a0  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+80) (BuildId: 5164298b53c3dd77d384cc114f454944fe9b469c)
      #07 pc 0000000000212520  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: c1533ab4f1f17e564063e13bf04bf126)
      #08 pc 00000000002f4730  /data/app/~~HFZQGcYyu4ci8IDxCxnGwA==/com.test.gl-de_4ToXawG4fZZeyZMpC3A==/oat/arm64/base.vdex (com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage+0)
      #09 pc 0000000000525528  /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1384) (BuildId: 5164298b53c3dd77d384cc114f454944fe9b469c)
      #10 pc 0000000000524f18  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+584) (BuildId: 5164298b53c3dd77d384cc114f454944fe9b469c)
      #11 pc 0000000000211608  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: c1533ab4f1f17e564063e13bf04bf126)
      #12 pc 00000000002f48be  /data/app/~~HFZQGcYyu4ci8IDxCxnGwA==/com.test.gl-de_4ToXawG4fZZeyZMpC3A==/oat/arm64/base.vdex (com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run+74)
      #13 pc 00000000001bf17c  /apex/com.android.art/javalib/arm64/boot.oat (java.lang.Thread.run+76) (BuildId: 715d0a044ea13bcf499cd6094001f85c3246944e)
      #14 pc 0000000000218964  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c1533ab4f1f17e564063e13bf04bf126)
      #15 pc 0000000000284208  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+188) (BuildId: c1533ab4f1f17e564063e13bf04bf126)
      #16 pc 000000000061fc44  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: c1533ab4f1f17e564063e13bf04bf126)
      #17 pc 000000000066e808  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1184) (BuildId: c1533ab4f1f17e564063e13bf04bf126)
      #18 pc 00000000000de0d4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: 86c2e03db5ccf75a523a17b3ca80de5c)
      #19 pc 000000000007a890  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 86c2e03db5ccf75a523a17b3ca80de5c)
E/tombstoned: Tombstone written to: tombstone_30
E/DataScoreUtil: handleNetlinkRecvKernelMessage
E/ListServiceUtils: checkInListByUid module:custom-icc uid:1000 cost 1230us return 0
E/TheiaManager: [tagL]: calling catchLog()..., focusedPid:3654 pids:[3654]
E/ORMS_HAL: open /dev/stune/foreground/schedtune.prefer_idle failed(No such file or directory)
E/BpTransactionCompletedListener: Failed to transact (-32)
 E/ANDR-PERF-JNI: UXEngine Trigger - Returning null
 E/ANDR-PERF-JNI: UXEngine Trigger - Returning null
E/ORMS_Platform : OplusResourceManagerPlatformUtils: readFile function exception:/sys/devices/platform/soc/5000000.qcom,kgsl-3d0/kgsl/kgsl-3d0/freq_table_mhz: open failed: ENOENT (No such file or directory)
E/oiface: get gpu freq table failed
E/oiface: client  not found, skipped
E/ORMS_Platform : OplusResourceManagerPlatformUtils: readFile function exception:/sys/devices/platform/soc/5000000.qcom,kgsl-3d0/kgsl/kgsl-3d0/freq_table_mhz: open failed: ENOENT (No such file or directory)
E/oiface: get gpu freq table failed
```
