### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by maka-io** [expo/expo#17340]
### Summary

$ npx pod-install
Scanning for pods...
1.11.3
> pod install
Auto-linking React Native modules for target `ProjectName`: Expo, RNCAsyncStorage, RNCMaskedView, RNCPicker, RNDateTimePicker, RNGestureHandler, RNReanimated, RNScreens, react-native-flipper, and react-native-safe-area-context
Analyzing dependencies
[!] Unable to find a specification for `ExpoModulesCore` depended upon by `Expo`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
      npm: 8.5.2 - ~/.nvm/versions/node/v14.18.3/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.67.4 => 0.67.4 
      react-native-web: ^0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.3
    Expo Workflow: bare

### Reproducible demo

`$ npx pod-install`
![Screen Shot 2022-05-04 at 7 11 02 PM](https://user-images.githubusercontent.com/3743882/166839869-1cd4d834-6a5f-4b71-9e78-88985ae7af67.png)

**Comment by byCedric** [comment]
Hi @maka-io! `expo-modules-core` is a direct dependency from `expo`, [you can see that here](https://www.npmjs.com/package/expo?activeTab=dependencies). If it's not installed, but you do have `expo@>=44`, then something must be wrong with your `node_modules` state. 

I would recommend reinstalling it, or validate it with:
- `$ npm list expo-modules-core`
- `$ yarn why expo-modules-core`

Hope this helps!

**Comment by maka-io** [comment]
Thank you @byCedric for the response!

I do not have expo-modules-core installed, and I do have expo@>=44.  I removed my node_modules folder, and reinstalled but the problem persists.

`npm list expo-modules-core` yields:
```
ProjectName@1.0.0 /.../ProjectName
└─┬ expo@44.0.6
  └── expo-modules-core@0.6.5
```

```
$ pod install
Auto-linking React Native modules for target `ProjectName `: Expo, RNCAsyncStorage, RNCMaskedView, RNCPicker, RNDateTimePicker, RNGestureHandler, RNReanimated, RNScreens, react-native-flipper, and react-native-safe-area-context
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Expo":
  In Podfile:
    Expo (from `../node_modules/expo/ios`)

Specs satisfying the `Expo (from `../node_modules/expo/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by coreybrown89** [comment]
So i'm actually having same issue when trying to build EAS via a github action. Also I am using the managed workflow.

**Comment by coreybrown89** [comment]
@byCedric I can't provide a repo, but `expo-modules-core` is not currently installed (to my knowledge). I was previously using SDK 43 with EAS building in a github action with no issues, after migrating to SDK 44 then to SDK 45 this issue started.

my current github action looks like this

```
name: EAS Build (Beta)
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build on EAS
        run: npx eas-cli build --platform all --profile beta --non-interactive
        env:
          APP_ENV: beta
```
