### ISSUE TITLE
Deep linking doesn't work when opening dev client

### ISSUE THREAD

**Issue by peteratdivvy** [expo/expo#20547]
### Summary

Hey y'all, bringing up an old question.

I need to open a deep link using expo dev build without showing an expo development interface.

Now I open a deep link and it asks me to choose which metro URL to use to refer the app link. Any ways around that?
I'm using this url to open an app:

`${appID}://expo-development-client/?url=${encodeURIComponent(url)}`;
with url :
`http://${host}:${port}/index.bundle?platform=${platform}&dev=true&minify=false&disableOnboarding=1&hot=true`

Seems like you can't pass in a deeplink url after the minify, dev, disableOnboarding, etc. params?

Would be nice if I could do something like:
http://${host}:${port}/index.bundle?platform=${platform}&dev=true&minify=false&disableOnboarding=1&hot=true&deepLinkUrl={myDeepLinkUrl}

Is there any way to allow deeplinking directly into the dev client? For context, i'm trying to run my Maestro tests locally and I need to pass a token into a URL in order to auth properly.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Package versions

```js
 "expo": "~47.0.8",
    "expo-application": "~5.0.1",
    "expo-constants": "~14.0.2",
    "expo-dev-client": "~2.0.1",
    "expo-device": "~5.0.0",
    "expo-document-picker": "~11.0.1",
    "expo-file-system": "~15.1.1",
    "expo-font": "~11.0.1",
    "expo-image-manipulator": "~11.0.0",
    "expo-image-picker": "~14.0.2",
    "expo-intent-launcher": "~10.3.1",
    "expo-linear-gradient": "~12.0.1",
    "expo-linking": "~3.2.3",
    "expo-mail-composer": "~12.0.0",
    "expo-modules-autolinking": "~1.0.0",
    "expo-notifications": "~0.17.0",
    "expo-sms": "~11.0.0",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.2",
    "expo-system-ui": "~2.0.1",
    "expo-updates": "~0.15.6",
    "expo-web-browser": "~12.0.0",
```

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 3.2.3 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.7.1
    Expo Workflow: bare

### Reproducible demo

I don't have reproducible demo, unfortunately.

**Comment by frankcalise** [comment]
Interested in knowing this as well, for now I created a subflow to resuse like this:

```yaml
# flow: ExpoDevClient
# intent:
#   Open up Expo's dev client menu and connect to
#   the locally running dev server

appId: infinitered.stage.ChainReactConf
---
- stopApp
- launchApp
- tapOn: "Enter URL manually"
- inputText: "http://localhost:8081?disableOnboarding=1"
- tapOn: "Connect"

```

and then a regular flow
```yaml
# flow: Welcome Screen

appId: infinitered.stage.ChainReactConf
---
- runFlow: subflows/ExpoDevClient.yaml
- assertVisible: "Welcome to Chain React.*"
```

**Comment by Brandon0330** [comment]
I'm also stuck at this problem. We would like to use our dev clients + EAS Update + dynamic API_URL from the deep-link, this way  we can re-use the same EAS branch with different back-end environments.

**Comment by graemegeorge** [comment]
> ```yaml
> - runFlow: subflows/ExpoDevClient.yaml
> ```

Thanks @frankcalise, this was a massive help to see an example. For some odd reason the `tapOn: Connect` didn't work and simply added the letter `g` to the end of my URL. Very odd.

Luckily the solution was to add an additional step `- hideKeyboard` which presumably acts like an `onBlur`? 🤷🏻‍♂️

Anyway, here is my working example:
```
appId: com.my.app
---
- launchApp
- tapOn: "Enter URL manually"
- inputText: "https://u.expo.dev/update/{id}?channel-name={channelName}&disableOnboarding=1"
- hideKeyboard # fixes an issue where cannot continue
- tapOn: Connect
```
and the regular flow (same as yours):
```
appId: com.my.app
---
- runFlow: subflows/ExpoDevClient.yaml
- assertVisible: Welcome
```

Works like a charm!! :D

**Comment by NorfeldtKnowit** [comment]
This worked for me

bundleIdentifier:


> maestro/onboarding.yaml

```
appId: com.my.app

---

- runFlow:
    file: "subflows/open-deep-link.yaml"
    env:
      ROUTE: "onboarding"
```

**Comment by moritzlang** [comment]
I am using this subflow to handle expo dev clients when launching the app:

```
appId: com.myapp
---
- launchApp:
    clearState: true
- runFlow:
    when:
      notVisible:
        id: SplashScreenLogo
    commands:
      - openLink:
          link: ${"com.myapp://expo-development-client/?url="+encodeURIComponent("http://localhost:8081/?disableOnboarding=1")}
- assertVisible:
    id: SplashScreenLogo
```

When the app is not starting (no splash screen is shown) I assume that the dev client is used and open the dev client with the local dev server url. This should make it work when not using a dev client as well.
