### ISSUE TITLE
[Expo-File-System] getInfoAsync returns size zero for hidden directories. 

### ISSUE THREAD

**Issue by raheemazeezabiodun** [expo/expo#26030]
### Minimal reproducible example

FileSystem.getInfoAsync("file:///storage/emulated/0/somePath/.hiddenDirectoryThatExists") returns size zero

### Summary

I'm using the expo-file-system to access files and directories, however for hidden directories, the size returned is zero and the files inside of the directory can't be fetched.

Here's what I have
```js
FileSystem.getInfoAsync("file:///storage/emulated/0/somePath/.hiddenDirectoryThatExists").then(
            resp => console.log(resp)
        ).catch(
            err => console.log("err", err)
        )

{"exists": true, "isDirectory": true, "modificationTime": 1702950649.164, "size": 0, "uri": "file:///storage/emulated/0/somePath/.hiddenDirectoryThatExists"}


// when I try to access the directory, it returns null
let dir = await FileSystem.readDirectoryAsync("file:///storage/emulated/0/somePath/.hiddenDirectoryThatExists");
console.log(dir); -> this logs  `[]`
```
For non-hidden directories, it returns the actual size and I can also access the files under the directory.

I can view the content of the hidden directory from my phone's file manager so it's accessible.

Test device is Google Pixel 7 pro, Android
,

### Environment

```yml  
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.11090377
    npmPackages:
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed
```
