### ISSUE TITLE
Export Web: ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [expo/expo#28695]
### Summary

```
expo export --platform web


Using (experimental) base path: /rocket-meals
Static rendering is enabled. Learn more: https://docs.expo.dev/router/reference/static-rendering/
Starting Metro Bundler
ReferenceError: Request is not defined
ReferenceError: Request is not defined
    at Object.<anonymous> (/home/runner/work/rocket-meals/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/server/src/environment.ts:23:28)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/runner/work/rocket-meals/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/server/install.js:1:28)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
```

### What platform(s) does this occur on?

Web

### SDK Version

51

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
      Watchman: 2023.11.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.0
      expo-router: ~3.5.10 => 3.5.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 7.4.0
    Expo Workflow: managed

### Minimal reproducible example

As i am only using `expo export --platform web`as provided by the documentation, do you realy need a github repo?

**Comment by marklawlor** [comment]
HI @NilsBaumgartner1994, I've closed this issue as there isn't enough information for us to assist you - but if you provide more I can reopen this issue.

If I run these commands to create a new repo, I'm unable to reproduce your issue.

```bash
npx create-expo-app@latest test-web-export --template default;
cd test-web-export;
npx expo export --platform web
```

This makes be believe there might be another issue, such a configuration setting with your `tsconfig.json` or a dependancy that is override the global TypeScript types.

For us to troubleshoot these issues we will need a Github repo to reproduce the issue

**Comment by NilsBaumgartner1994** [comment]
@marklawlor running this on my computer resulted in no error. I found that this only occurs in the GH-Action pipeline:

```
Run git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

> rocket-meals-dev@1.0.0 deploy:gh:pages
> npm run export:web && gh-pages -t -d dist -u github-actions-bot <support+actions@github.com>


> rocket-meals-dev@1.0.0 export:web
> expo export --platform web


Using (experimental) base path: /rocket-meals
Static rendering is enabled. Learn more: https://docs.expo.dev/router/reference/static-rendering/
Starting Metro Bundler
ReferenceError: Request is not defined
ReferenceError: Request is not defined
    at Object.<anonymous> (/home/runner/work/rocket-meals/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/server/src/environment.ts:23:28)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/runner/work/rocket-meals/rocket-meals/frontend/rocket-meals-dev/node_modules/@expo/server/install.js:1:28)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Error: Process completed with exit code 1.
```


GH Action script:

```
name: GH-Pages Publish
on:
  push:
    branches:
      - main
      - master
      - web
      - production
    paths:
      - 'frontend/rocket-meals-dev/**'
      - ".github/workflows/frontend_native_expo.yml"
      
jobs:
  gh-pages:
    defaults:
      run:
        working-directory: ./frontend/rocket-meals-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: git config --global user.name 'Rocket Meals'
      - run: git config --global user.email 'nils@baumgartner-software.de'
      #https://www.npmjs.com/package/gh-pages
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          CI=false npm run deploy:gh:pages -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any

```

**Comment by NilsBaumgartner1994** [comment]
from package.json
```
 "deploy:gh:pages": "npm run export:web && gh-pages -t -d dist",
```

**Comment by NilsBaumgartner1994** [comment]
@marklawlor The problem was the specific node version:

18.x did not worked.
```
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
```

Instead version 18.19.1 worked:

```
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'
```

I should have read: https://expo.dev/changelog/2023/11-03-node-default
