### ISSUE TITLE
Expo projects in v~51.0.18 built with Bun do not run in Android

### ISSUE THREAD

**Issue by the-simian** [expo/expo#30234]
### Minimal reproducible example

https://github.com/the-simian/repro-expo-bun-android-bug

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When scaffolding a fresh project with `bun create expo my-app` the application will experience a runtime issue on Android. The web-export does still work correctly. 
Also, scaffolding in the same way with npm will run successfully. Installing with npm and using the bun runtime also works just fine. The issue is when you *install* with bun.

Provided is a minimal reproduceable example, that essentially follows the steps here: `https://docs.expo.dev/guides/using-bun/`

Here's the steps to use the project I have linked:

#Reproduce failing mobile build:
1. `git clone git@github.com:the-simian/repro-expo-bun-android-bug.git`
2. `bun install`
3. `bun start` . In my case I pressed s to use Go.
4. take a picture of the Qr code.
5. Android will bundle, as it does normally, and seems to succeed in this step.
    a. `Android Bundled 4320ms node_modules/expo-router/entry.js (1146 modules)`
6. At runtime you will see two errors:
```sh
 ERROR  Error: Creating a navigator doesn't take an argument. Maybe you are trying to use React Navigation 4 API? See https://reactnavigation.org/docs/hello-react-navigation for the latest API and guides., js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

![image](https://github.com/expo/expo/assets/954596/bb581754-7ba3-448e-9083-43228ca61b38)

here are the two Red Screens:

|  Invariant Violation: "main" has not been registered.  | Creating a navigator doesn't take an argument. |
|--------|--------|
| ![image](https://github.com/expo/expo/assets/954596/bd550b37-2d76-4ea7-bdfc-6d5e6843017a)| ![image](https://github.com/expo/expo/assets/954596/eaba4fcb-aa8c-4442-adaf-e1c3718b3483)| 

### Environment

```yaml
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 22.4.0 - ~/.nvm/versions/node/v22.4.0/bin/node
      npm: 10.8.1 - ~/.nvm/versions/node/v22.4.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 29
        Build Tools: 30.0.1
    npmPackages:
      expo: ~51.0.18 => 51.0.18
      expo-router: ~3.5.17 => 3.5.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed
 ```
