### ISSUE TITLE
Expo build error in AWS amplify

### ISSUE THREAD

**Issue by Amazing1974** [expo/expo#34151]
### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### I'm getting the below error when I publish my expo web app to AWS amplify

<img width="1231" alt="Image" src="https://github.com/user-attachments/assets/5bb77f80-9c87-45aa-b3ae-16e223f0acec" />

### amplify.yml
```
version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - npm install --quiet --global expo-cli
        - >
          if [ -f yarn.lock ]; then
            yarn
          elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install
          fi
    build:
      commands:
        - expo build:web
  artifacts:
    baseDirectory: web-build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - $(npm root --global)/**/*
```

### And it's my app structure.

<img width="289" alt="Image" src="https://github.com/user-attachments/assets/a922ed41-6639-49d9-8da3-01b1c5793755" />

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.1 - /usr/local/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v21.6.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.10 => 52.0.10 
      expo-router: ~4.0.8 => 4.0.8 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.6 => 0.19.13 
    Expo Workflow: managed
```
