### ISSUE TITLE
EAS submit failed with: Input parameter "changes_not_sent_for_review" for step "cc28e3ab-017a-44f0-aa02-43f4e12b7066" must be of type "boolean".

### ISSUE THREAD

**Issue by dianamelga** [expo/expo#35448]
### Summary

I am using EAS workflow to submit a new build for both Android and iOS. But the submission on Android is failing at the **Create Submission Entity** step with this error: 
`Input parameter "changes_not_sent_for_review" for step "cc28e3ab-017a-44f0-aa02-43f4e12b7066" must be of type "boolean".`

This is my eas.json (I am making sure to add `changesNotSentForReview` despite that value not being required as mentioned [here](https://docs.expo.dev/eas/json/#changesnotsentforreview)):
```
{
  "cli": {
    "version": ">= 10.0.2",
    "appVersionSource": "remote"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "buildArtifactPaths": ["ios/build/*"]
      },
      "env": {
        "APP_VARIANT": "development"
      },
      "channel": "development"
    },
    "preview": {
      "distribution": "internal",
      "ios": {
        "simulator": false,
        "buildArtifactPaths": ["ios/build/*"]
      },
      "android": {
        "buildType": "apk"
      },
      "env": {
        "APP_VARIANT": "preview"
      },
      "channel": "preview"
    },
    "production": {
      "ios": {
        "buildArtifactPaths": ["ios/build/*"]
      },
      "android": {
        "buildType": "app-bundle"
      },
      "autoIncrement": true,
      "env": {
        "APP_VARIANT": "production"
      },
      "channel": "production"
    },
    "development-simulator": { //https://docs.expo.dev/develop/development-builds/create-a-build/
      "extends": "development",
      "ios": {
        "simulator": true
      }
    }
  },
  "submit": {
    "production": {
      "android": {
        "serviceAccountKeyPath": "./service-account-file.json",
        "track": "internal",
        "changesNotSentForReview": false
      }, 
      "ios": {
        "ascAppId": "xxxxxxx"
      }
    }
  }
}
```
and this is my workflow:
```
name: Deploy to production

on:
  push:
    branches: ['development'] # later modify to be only main

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint
  get_android_build:
    name: Check for existing android build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: production
  get_ios_build:
    name: Check for existing ios build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: production
  build_android:
    name: Build Android
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: production
  build_ios:
    name: Build iOS
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: production
  submit_android_build:
    name: Submit Android Build
    needs: [build_android]
    type: submit
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
  submit_ios_build:
    name: Submit iOS Build
    needs: [build_ios]
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
  publish_android_update:
    name: Publish Android update
    needs: [get_android_build]
    if: ${{ needs.get_android_build.outputs.build_id }}
    type: update
    params:
      branch: production
      platform: android
  publish_ios_update:
    name: Publish iOS update
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    type: update
    params:
      branch: production
      platform: ios
```
Summary of the build right before jumping to the submission step:

<img width="625" alt="Image" src="https://github.com/user-attachments/assets/456db693-0a2d-4f5b-a6a4-8574a2f4458c" />

Error evidence:

<img width="1207" alt="Image" src="https://github.com/user-attachments/assets/1fbfc7de-2041-42e9-b6fb-98610af89215" />

### What platform(s) does this occur on?

Android

### SDK Version

52.0.37

### Environment

```text
expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.3.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 22.12.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.9.0 - /usr/local/bin/npm
      Watchman: 2024.12.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/diana/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 33, 34, 35
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-21 | Google APIs Intel x86_64 Atom, android-28 | Intel x86_64 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86_64 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86_64 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86_64 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64, android-33 | Wear OS 4 Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom, android-34 | Wear OS 5 Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom, android-35 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.37 => 52.0.37 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.7 => 0.76.7 
    npmGlobalPackages:
      eas-cli: 15.0.14
    Expo Workflow: managed
```

### Minimal reproducible example

In order to reproduce this, you just need to trigger my exact same workflow provided above in any expo project with that same eas.json, and of course registering your expo project.

Not sure if this helps, but the issue seems to be triggered [here](https://github.com/expo/eas-build/blob/a199928a10e8c6f9e19da0f47bbcda92234a64c8/packages/steps/src/BuildStepInput.ts#L239)
