### ISSUE TITLE
eas build but can't find local modules

### ISSUE THREAD

**Issue by Jinx-1120** [expo/expo#37527]
### Minimal reproducible example

I use yarn workspace for project management, and its directory structure is similar to
```
├── apps
│   ├── backend
│   └── mobile
├── Dockerfile
├── eslint.config.mjs
├── package.json
├── packages
│   ├── expo-xxx-plus
│   └── native-addons
├── README.md
├── tsconfig.json
├── turbo.json
└── yarn.lock
```
But when I execute eas build --platform ios --profile preview --non-interactive --no-wait in the mobile directory under ci, the build will fail:
Build failed
```
Cannot find module './plugin/build'
Require stack:
- /Users/expo/workingdir/build/packages/expo-xxx-plus/app.plugin.js
- /usr/local/eas-build-worker/node_modules/@expo/config/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
- /usr/local/eas-build-worker/node_modules/@expo/config/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
- /usr/local/eas-build-worker/node_modules/@expo/config/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
- /usr/local/eas-build-worker/node_modules/@expo/config/node_modules/@expo/config-plugins/build/index.js
- /usr/local/eas-build-worker/node_modules/@expo/config/build/plugins/withConfigPlugins.js
- /usr/local/eas-build-worker/node_modules/@expo/config/build/Config.js
- /usr/local/eas-build-worker/node_modules/@expo/config/build/index.js
...

```
my mobile packages.json
```
"dependencies": {
  "expo-xxx-plus": "workspace:^",
}
```

### Steps to reproduce

development.yml
```yml
name: Build iOS for development

on:
  push:
    branches:
      - main
    paths:
      - "apps/mobile/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build iOS Preview IPA for device
    if: github.secret_source != 'None'
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/workflows/install_dependencies

      - name: 📱 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🔨 Build iOS IPA
        working-directory: apps/mobile
        run: eas build --platform ios --profile preview --non-interactive --no-wait
        env:
          CI: true
```

install_dependencies.yml
```
name: 'Install dependencies'
description: 'Install nodejs, rust and dependencies packages'
runs:
  using: 'composite'
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: yarn
    - name: Install yarn dependencies
      run: |
        yarn install --check-cache
        yarn install --immutable
        yarn workspace expo-xxx-plus prepare
      shell: bash
```

expo-xxx-plus directory structure is similar to
```
.
├── android
│   ├── build
│   ├── build.gradle
│   ├── local.properties
│   ├── proguard-rules.pro
│   └── src
├── ANDROID_CONFIG.md
├── app.json
├── app.plugin.js
├── build
│   ├── ExpoAnalyticsModule.d.ts
│   ├── ExpoAnalyticsModule.d.ts.map
│   ├── ExpoAnalyticsModule.js
│   ├── ExpoAnalyticsModule.js.map
│   ├── ExpoPushModule.d.ts
│   ├── ExpoPushModule.d.ts.map
│   ├── ExpoPushModule.js
│   ├── ExpoPushModule.js.map
│   ├── index.d.ts
│   ├── index.d.ts.map
│   ├── index.js
│   └── index.js.map
├── CHANGELOG.md
├── expo-module.config.json
├── ios
│   ├── ExpoAnalyticsModule.swift
│   ├── ExpoPlus.podspec
│   ├── ExpoPushModule.swift
│   └── Records.swift
├── package.json
├── plugin
│   ├── build
│   ├── src
│   ├── tsconfig.json
│   └── tsconfig.tsbuildinfo
├── README.md
├── src
│   ├── ExpoAnalyticsModule.ts
│   ├── ExpoModule.ts
│   └── index.ts
└── tsconfig.json
```
package.json
```json
{
  "name": "expo-umeng-plus",
  "version": "0.1.0",
  "description": "umeng plus",
  "main": "build/index.js",
  "types": "build/index.d.ts",
  "scripts": {
    "build": "npm run build:plugin && expo-module build",
    "build:plugin": "tsc -p plugin",
    "clean": "expo-module clean && rm -rf plugin/build",
    "lint": "expo-module lint",
    "prepare": "expo-module prepare",
    "prepublishOnly": "expo-module prepublishOnly",
    "expo-module": "expo-module",
    "open:ios": "xed example/ios",
    "open:android": "open -a \"Android Studio\" example/android",
    "android": "expo run:android",
    "ios": "expo run:ios"
  },
  "keywords": [
    "react-native",
    "expo",
    "expo-umeng-plus",
    "ExpoUmengPlus"
  ],
  "repository": "https://github.com/xxx",
  "bugs": {
    "url": "https://github.com/xxxx"
  },
  "author": "jinx-1120 <jinhaidi01@gmail.com> (https://github.com/Jinx-1120)",
  "license": "MIT",
  "homepage": "https://github.com/xxxx",
  "devDependencies": {
    "@expo/config-plugins": "^8.0.0",
    "@types/react": "~19.0.0",
    "expo": "~53.0.0",
    "expo-module-scripts": "^4.1.6",
    "react-native": "0.79.1",
    "typescript": "^5.0.0"
  },
  "peerDependencies": {
    "expo": "*",
    "react": "*",
    "react-native": "*"
  },
  "dependencies": {
    "expo": "~53.0.11",
    "react": "19.0.0",
    "react-native": "0.79.3"
  }
}

```
.gitignore
```
# OSX
#
.DS_Store

# VSCode
.vscode/
jsconfig.json

# Xcode
#
build/
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
xcuserdata
*.xccheckout
*.moved-aside
DerivedData
*.hmap
*.ipa
*.xcuserstate
project.xcworkspace

# Android/IJ
#
.classpath
.cxx
.gradle
.idea
.project
.settings
local.properties
android.iml
android/app/libs
android/keystores/debug.keystore

# Cocoapods
#
example/ios/Pods

# Ruby
example/vendor/

# node.js
#
node_modules/
npm-debug.log
yarn-debug.log
yarn-error.log

# Expo
.expo/*

```

app.plugin.js
```js
module.exports = require('./plugin/build')
```

tsconfig.json
```json
{
  "extends": "expo-module-scripts/tsconfig.base",
  "compilerOptions": {
    "outDir": "./build",
    "typeRoots": ["./node_modules/@types", "../../node_modules/@types"],
    "types": ["jest"]
  },
  "include": ["./src"],
  "exclude": ["**/__mocks__/*", "**/__tests__/*"]
}
```

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.6.0 - ~/.volta/tools/image/node/22.6.0/bin/node
      Yarn: 4.7.0 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - ~/.volta/tools/image/node/22.6.0/bin/npm
      Watchman: 2025.02.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.5, iOS 18.5, macOS 15.5, tvOS 18.5, visionOS 2.5, watchOS 11.5
      Android SDK:
        API Levels: 31, 33, 34, 35
        Build Tools: 30.0.2, 30.0.3, 33.0.3, 34.0.0, 35.0.0
        System Images: android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23726.103.2422.12816248
      Xcode: 16.4/16F6 - /usr/bin/xcodebuild
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
env: load .env.local
13/15 checks passed. 2 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Check for app config fields that may not be synced in a non-CNG project
This project contains native project folders but also has native configuration properties in app.config.ts, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: orientation, icon, scheme, userInterfaceStyle, ios, android, androidStatusBar, plugins. 

Advice:
Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

✖ Validate packages against React Native Directory package metadata
The following issues were found when validating your dependencies against React Native Directory:
  Untested on New Architecture: immer
  No metadata available: @react-native-vector-icons/common, @react-native/metro-config, @tanstack/query-sync-storage-persister, @tanstack/react-query-persist-client, @tanstack/react-table, expo-module-scripts, expo-xxx-plus, highlight-words-core, marked, neverthrow, node-html-parser, polished, react-native-portalize, socket.io-client, superjson
Advice:
Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

2 checks failed, indicating possible issues with the project.
```
