### ISSUE TITLE
[android][permissions] Permissions for CAMERA_ROLL does not return granted for standalone Android

### ISSUE THREAD

**Issue by michalgarcarz** [expo/expo#6173]
### Environment
Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.4.1

### Steps to Reproduce
React native app with expo/managed flow. With expo everything is working fine, on standalone app(Android) with the following code:

```
 const verifyPermissions = async () => {
        const result = await Permissions.askAsync(
            Permissions.CAMERA_ROLL,
            Permissions.CAMERA
        );
        if (result.status !== 'granted') {
            Alert.alert(
                'Insufficient permissions!',
                'You need to grant camera permissions to use this app.',
                [{ text: 'Okay' }]
            );
            return false;
        }
        return true;
    };
```
I do always get the alarm. In App settings (view from Android/application details) i do see Camera permissions. In app.json i do have:

```
"android": {
      "package": "mypackage",
      "versionCode": 4,
      "permissions": [
        "CAMERA_ROLL",
        "CAMERA"
      ],
      "config": {
        "googleSignIn": {
          "apiKey": "AIzaSyDMQwetfV-CBxI3o7VlPUYkvC5Pxxx",
          "certificateHash": "7E27689E195162E1D59CD581505B05xxxx"                             
        }
      }
    }
```

### Expected Behavior

No alarm, permissions granted.

### Actual Behavior

Alarm - can not get CAMERA + CAMERA_ROLL permissions (i have also tried just CAMERA and have the same issue).

Update, what is also interesting i do not see CAMERA permissions in corresponding apk file extracted via bundletool from expo aab build:

```
aapt debug badging base-arm64_v8a.apk 
package: name='xxx' versionCode='5' versionName='' split='config.arm64_v8a'
application: label='' icon=''
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-implied-permission: name='android.permission.WRITE_EXTERNAL_STORAGE' reason='targetSdkVersion < 4'
uses-permission: name='android.permission.READ_PHONE_STATE'
uses-implied-permission: name='android.permission.READ_PHONE_STATE' reason='targetSdkVersion < 4'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission: name='android.permission.READ_EXTERNAL_STORAGE' reason='requested WRITE_EXTERNAL_STORAGE'
feature-group: label=''
  uses-feature: name='android.hardware.faketouch'
  uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
supports-screens: 'normal'
supports-any-density: 'false'
locales:
densities:
native-code: 'arm64-v8a'

```

What's wrong here ? Should not i see CAMERA permissions with that debug ?
(the above debug is a result of additional "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE" permissions attached to app.json, while "CAMERA" permissions is also still in my app.json i do not see it in this debug)

Thanks,
