### ISSUE TITLE
exp publish throws 'socket hang up' exception on gitlab CI

### ISSUE THREAD

**Issue by vardium** [expo/expo#909]
I am trying to prepare a 'Continuous Integration' environment for my expo project. On gitlab CI, I am getting following exception on exp publish.

```
$ exp login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}

Success. You are now logged in as ****.

$ exp publish
[exp] Unable to find an existing exp instance for this directory, starting a new one...
[exp] 
[exp] Starting React Native packager...
[exp] Scanning folders for symlinks in /builds/****/****/node_modules (13ms)
[exp] Loading dependency graph.
[exp] Running packager on port 19001.
[exp] Publishing...
[exp] Building iOS bundle
[exp] socket hang up
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.
ERROR: Job failed: exit code 1
```

Here is my .gitlab-ci.yml configuration :

```
image: node:6.11.0

stages:
  - build
  - deploy

before_script:
  - npm i -g exp --silent

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules/

build:
  stage: build
  script:
    - npm i --silent

deploy:
  stage: deploy
  only:
    - master
    - /^release\/.*$/
  script:
    - exp login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}
    #- exp build:android
    - exp publish

```
